import OpCodes

wordToOpCode = {
    "ㅇㅈㄱㅇ" : OpCodes.Op_Add,
    "오지구요" : OpCodes.Op_Add,
    "ㅈㄹㄱㅇ" : OpCodes.Op_Substract,
    "지리구요" : OpCodes.Op_Substract,
    "ㄱㅇㄷ" : OpCodes.Op_Multiply,
    "개이득" : OpCodes.Op_Multiply,
    "에바" : OpCodes.Op_Divide,
    "ㄴㄴ" : OpCodes.Op_Type_Move_Left,
    "노노" : OpCodes.Op_Type_Move_Left,
    "ㅇㅇ" : OpCodes.Op_Type_Move_Right,
    "이응" : OpCodes.Op_Type_Move_Right,
    "ㅅㅌㅊ" : OpCodes.Op_Memory_Move_Up,
    "상타치" : OpCodes.Op_Memory_Move_Up,
    "ㅎㅌㅊ" : OpCodes.Op_Memory_Move_Down,
    "하타치" : OpCodes.Op_Memory_Move_Down,
    "ㄱㄱ" : OpCodes.Op_Stack_Push,
    "고고" : OpCodes.Op_Stack_Push,
    "ㅂㅂ" : OpCodes.Op_Stack_Pop,
    "바바" : OpCodes.Op_Stack_Pop,
    "낄끼" : OpCodes.Op_List_Insert,
    "빠빠" : OpCodes.Op_List_Delete,
    "ㅇㅈ?" : OpCodes.Op_Condition_Begin,
    "인정?" : OpCodes.Op_Condition_Begin,
    "ㅇ!ㅇㅈ" : OpCodes.Op_Condition_End,
    "어!인정" : OpCodes.Op_Condition_End,
    "응!인정" : OpCodes.Op_Condition_End,
    "인지용" : OpCodes.Op_Condition_End,
    "^^7" : OpCodes.Op_Remark,
    "창렬" : OpCodes.Op_Num_0,
    "혜자" : OpCodes.Op_Num_1,
    "뇌피셜" : OpCodes.Op_Input,
    "오피셜" : OpCodes.Op_Ouput,
}